version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Navigo nella cartella della Lambda..."
      - cd lambda/update_database
      - echo "Zippo update_database.py in lambda_upd_db.zip..."
      - zip -r lambda_upd_db.zip update_database.py
artifacts:
  files:
    - lambda/update_database/lambda_upd_db.zip
  discard-paths: yes